site_name: Portfolio
site_author: Kacper Szaruga
site_description: >-
    Oto portfolio moich projektów z Data Science i AI!

repo_name: Kacper-77/portfolio
repo_url: https://github.com/Kacper-77/portfolio

theme:
  name: material
  palette:
    primary: cyan

nav:
- Strona Domowa: index.md
- Projekty:
  - "Iris": iris/index.md
  - "Titanic": titanic/index.md
  - "Recipes-io": recipes-io/index.md
  - "Pomagacz językowy": lng-helper/index.md